### ISSUE TITLE
Add react-transform-display-name

### ISSUE THREAD

**Issue by greypants** [danmartinez101/babel-preset-react-hmre#11]
Might be a good idea to add react-transform-display-name to fix the `ProxyClass` issue, at least until https://github.com/gaearon/babel-plugin-react-transform/issues/19 is resolved. 

See https://github.com/gaearon/babel-plugin-react-transform/issues/19#issuecomment-166979686 for details.

**Comment by danmartinez101** [comment]
Following the chain:
https://github.com/gaearon/babel-plugin-react-transform/issues/19#issuecomment-167160916
https://github.com/gaearon/babel-plugin-react-transform/issues/67#issuecomment-167444115
https://github.com/babel/babel/pull/3216#issuecomment-167444704 

It looks like this should be fixed? I'm not 100% up to speed on the actual issue, but I'll look into it in the next day or so. If you could verify that https://github.com/babel/babel/pull/3216 has not resolved this it will help a bit. Thanks!

**Comment by greypants** [comment]
Still seems like an issue... I'm on the latest releases of the following:

```
"babel-core": "6.5.1",
"babel-loader": "6.2.2",
"babel-preset-react-hmre": "1.1.0",
```

Still getting `ProxyClass` in my errors instead of the proper `displayName`
![image](https://cloud.githubusercontent.com/assets/647549/12962325/f5d2cbb0-d012-11e5-90da-acdcb404481e.png)

**Comment by danmartinez101** [comment]
Can you provide some code that produces the type of errors you see there? If I'm going to add to the preset, I'd like to add the use cases as tests.

**Comment by danmartinez101** [comment]
After some thought, I've decided to close this issue. I'd like to keep it as small as possible. The main goal is to encapsulate the configuration for react-transform. In the event that a user desires to extend what is provided by this preset, the recommended approach is to use the source as a reference and include it in the users project directly. I will update the documentation to express this recommendation soon.

**Comment by greypants** [comment]
Sounds good. Thanks.

**Comment by gaearon** [comment]
Can’t reproduce this in the latest version of https://github.com/gaearon/react-transform-boilerplate:

<img width="485" alt="screen shot 2016-03-06 at 03 44 42" src="https://cloud.githubusercontent.com/assets/810438/13552152/da618ad0-e34d-11e5-9fdd-975606379937.png">

I would suggest checking your plugin order and updating all related packages (including Babel).
